management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

logging:
  level:
    root: WARN
    com.example.drone: INFO
    org.springframework.web: WARN
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
