server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always
    include-exception: true

logging:
  level:
    root: INFO
    com.example.drone: DEBUG
    org.springframework.kafka: DEBUG
    org.apache.kafka: INFO

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true
    path: /swagger-ui
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    display-request-duration: true
    show-extensions: true
